node {
    dir('jenkins') {
        git url: 'https://github.com/theocincotta/jenkins.git'
    }

    sh('ls')
    sh('ls jenkins/pipeline/jenkins/theo-test/build.sh')
    sh('bash jenkins/pipeline/jenkins/theo-test/build.sh')
}
