node {
    checkout scm
    dir('jenkins-github-test') {
        git url: 'https://github.com/theocincotta/jenkins.git'
    }
}

pipeline {
    agent {
        label any
    }

    stages {
        stage('build') {
            steps {
                sh('bash jenkins/pipeline/jenkins/theo-test/build.sh')
            }
        }
    }
}

